### ISSUE TITLE
Support for v15 shader cache

### ISSUE THREAD

**Issue by SwiftyPop** [oltolm/dxvk-cache-tool#1]
When I try creating the output for v15 shader cache, I got this error:
`Detected state cache version 15`
`Error. Exiting: dxvk_cache_tool.nim(105, 15) header.version == 8 or header.version == 9 or header.version == 10 only versions 8-10 are supported, exiting`

Seems like it's only you who provide this tool for Windows, I hoping you support it.

**Comment by oltolm** [comment]
OK, I published a new release.

**Comment by SwiftyPop** [comment]
> OK, I published a new release.

@oltolm Thanks but seems like it failed to merge and got this error: 
```
dxvk_cache_tool INSIDE.dxvk-cache INSIDE2.dxvk-cache
Merging files INSIDE.dxvk-cache INSIDE2.dxvk-cache
Detected state cache version 15
Merging INSIDE.dxvk-cache (1/2)...
Error. Exiting: cannot read from stream
```

**Comment by oltolm** [comment]
I don't know what the problem is. I tested it briefly and it worked. Make sure the files actually exist.

**Comment by SwiftyPop** [comment]
@oltolm Seems like it's my problem. I tried the tool in other game cache and it works just fine. Thanks :)
